### ISSUE TITLE
Support Gmail app as well?

### ISSUE THREAD

**Issue by ankushg** [magn2o/KissMyPass#1]
This is super annoying for me too, but I use Google's Gmail app since it has push notifications. Any chance you could add support for Gmail too? If you want, I could make a pull request.

**Comment by magn2o** [comment]
Sure, I'll get that added. I just need to get the identifier used. Look for
v1.1 soon. :)

Sent from my iPhone

On Mar 16, 2015, at 4:17 PM, Ankush Gupta notifications@github.com wrote:

This is super annoying for me too, but I use Google's Gmail app since it
has push notifications. Any chance you could add support for Gmail too? If
you want, I could make a pull request.

—
Reply to this email directly or view it on GitHub
https://github.com/magn2o/KissMyPass/issues/1.

**Comment by ankushg** [comment]
Thanks for the update!

Fixed as of https://github.com/magn2o/KissMyPass/commit/3d87957c41d6dad5c3979703d266ae6e91c09de3
